######################################################################
# Automatically generated by qmake (2.01a) dom out 7 19:18:58 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mw.h
SOURCES += main.cpp
