######################################################################
# Automatically generated by qmake (2.01a) sáb jan 16 07:41:20 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
