######################################################################
# Automatically generated by qmake (2.01a) sex nov 9 15:18:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp
