######################################################################
# Automatically generated by qmake (2.01a) sáb jan 16 07:53:25 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mw.h
SOURCES += main.cpp
