#!/bin/bash

gcc -Wall -fPIC -c $1.c
gcc -shared -Wl,-soname,lib$1.so.1 -o lib$1.so.1.0 $1.o
ln -sf libctest.so.1.0 libctest.so
ln -sf libctest.so.1.0 libctest.so.1
gcc -Wall -o cprog cprog.c -ldl
export LD_LIBRARY_PATH=.
