######################################################################
# Automatically generated by qmake (2.01a) qui out 11 19:58:56 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
