######################################################################
# Automatically generated by qmake (2.01a) sáb jan 16 07:31:36 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += LsWin.hpp
SOURCES += main.cpp
