######################################################################
# Automatically generated by qmake (2.01a) sáb out 6 16:00:18 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mw.h
SOURCES += main.cpp
