######################################################################
# Automatically generated by qmake (2.01a) qua out 24 03:02:26 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
