######################################################################
# Automatically generated by qmake (2.01a) qua nov 7 22:04:23 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += splash.h
SOURCES += main.cpp
