######################################################################
# Automatically generated by qmake (2.01a) sáb jan 16 07:44:07 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += db.h mw.h
SOURCES += main.cpp
