######################################################################
# Automatically generated by qmake (2.01a) sex set 2 03:46:11 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += filewindow.h mw.h ts.h tw.h widget.h
SOURCES += main.cpp
