######################################################################
# Automatically generated by qmake (2.01a) qua nov 7 22:07:17 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
