######################################################################
# Automatically generated by qmake (2.01a) sáb jan 16 07:50:48 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += inipt.h mw.h
SOURCES += main.cpp
