######################################################################
# Automatically generated by qmake (2.01a) qui out 11 15:54:09 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
