######################################################################
# Automatically generated by qmake (2.01a) qua set 25 00:50:49 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += app.h
SOURCES += main.cpp
