######################################################################
# Automatically generated by qmake (2.01a) qui jan 31 15:07:09 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
