######################################################################
# Automatically generated by qmake (2.01a) sex set 2 03:45:28 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
